CREATE TABLE PROPRIETARIO(

PRO_ID      NUMBER NOT NULL,
PRO_NOME    VARCHAR(80) NOT NULL,
PRO_RG      VARCHAR(15) NOT NULL,
PRO_CPF     VARCHAR(15) NOT NULL,
PRO_EMAIL   VARCHAR(50) NOT NULL,
PRO_DT_NASC      DATE NOT NULL,
PRO_DDD_TELEFONE VARCHAR (15) NOT NULL,
CONSTRAINT PK_PROPRIETARIO PRIMARY KEY (PRO_CPF,PRO_ID)
)

CREATE TABLE VEICULO(
VEI_ID       NUMBER NOT NULL
VEI_DESRICAO VARCHAR(80) NOT NULL,
VEI_PLACA    VARCHAR(10) NOT NULL
FK_MAR_ID    NUMBER_NOT NULL,
FK_PRO_ID    NUMBER_NOT NULL,
FK_MUN_ID    NUMBER_NOT NULL,
FK_EST_ID    NUMBER_NOT NULL,
FK_CAT_ID    NUMBER_NOT NULL,
CONSTRAINT PK_PROPRIETARIO PRIMARY KEY (VEI_ID,FK_PRO_ID),
CONSTRAINT FK_FK_MAR_ID FOREIGN KEY (FK_MAR_ID)
    REFERENCES MARCA(MAR_ID),
CONSTRAINT FK_FK_PRO_ID FOREIGN KEY (FK_PRO_ID)
    REFERENCES PROPRIETARIO(PRO_ID),
CONSTRAINT FK_FK_MUN_ID FOREIGN KEY (FK_MUN_ID)
    REFERENCES MUNICIPIO(MUN_ID),
CONSTRAINT FK_FK_EST_ID FOREIGN KEY (FK_EST_ID)
    REFERENCES ESTADOO(EST_ID),
CONSTRAINT FK_FK_CAT_ID FOREIGN KEY (FK_CAT_ID)
    REFERENCES MARCA(CAT_ID)
)

CREATE TABLE MARCA(
MAR_ID   NUMBER NOT NULL,
MAR_DESCRICAO   VARCHAR(50) NOT NULL,
CONSTRAINT PK_PROPRIETARIO PRIMARY KEY (MAR_ID,MAR_DESCRICAO)
),

CREATE TABLE CATEGORIA(
CAT_ID   NUMBER NOT NULL
CAT_DESCRICAO   VARCHAR(50) NOT NULL,
CONSTRAINT PK_PROPRIETARIO PRIMARY KEY (CAR_ID,CAT_DESCRICAO)
),

CREATE TABLE CATEGORIA(
MUN_ID   NUMBER NOT NULL,
MUN_DESCRICAO   VARCHAR(50) NOT NULL,
CONSTRAINT PK_PROPRIETARIO PRIMARY KEY (MUN_ID,MUN_DESCRICAO)
),

CREATE TABLE ESTADO(
EST_ID   NUMBER NOT NULL,
EST_DESCRICAO   VARCHAR NOT NULL,
FK_MUN_ID   NUMBER(50) NOT NULL,
CONSTRAINT PK_PROPRIETARIO PRIMARY KEY (MAR_ID,MAR_DESCRICAO),
CONSTRAINT FK_FK_MUN_ID FOREIGN KEY (MUN_ID)
    REFERENCES Persons(FK_MUN_ID)
),






